import Head from "next/head";
import { Inter } from "@next/font/google";
import {HomeHeader} from "../component/layout/header/header";
import InitialBanner from "../component/banner/InitialBanner";
import ConnectSection from "../component/ConnectSection/connectSection";
import CronosHub from "../component/cronosHub/cronosHub";
import DescriptionHub from "../component/descriptionHub/descriptionHub";
import HedronSection from "../component/hedron/hedron";
import JointWork from "../component/jointWork/jointWork";
import Technology from "../component/technology/technology";
import Footer from "@/component/layout/footer/footer";
import EnterEmail from "@/component/enterEmail/enterEmail";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>EXCHANGE Crypto | Argentina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader/>
      <InitialBanner/>
      <ConnectSection/>
      <CronosHub/>
      <DescriptionHub/>
      <HedronSection/>
      <Technology/>
      <JointWork/>
      <EnterEmail/>
      <Footer/>
    </>
  );
}
